### ISSUE TITLE
Support for deerma.humidifier.jsq

### ISSUE THREAD

**Issue by mac8005** [russtone/homebridge-mi-humidifier#47]
Hi @russtone 
Would it be possible to add support for deerma.humidifier.jsq?
That would be awesome!

Thank you

**Comment by russtone** [comment]
hey, @mac8005,

As I see here https://github.com/rytilahti/python-miio/blob/master/miio/airhumidifier_mjjsq.py,
`deerma.humidifier.jsq`, `deerma.humidifier.jsq1` and `deerma.humidifier.mjjsq` all have same methods. `deerma.humidifier.mjjsq` is already supported by this plugin. So, you can set model to `deerma.humidifier.mjjsq` and it should work.

Please, test it on the new beta version I've published.

To install it you need to run `npm install -g homebridge-mi-humidifier@latest`.
Also, configuration is changed, please check the example here https://www.npmjs.com/package/homebridge-mi-humidifier/v/2.0.0-beta.2

**Comment by mac8005** [comment]
Just tried now. Turning on/off works but temperature and humidity is alway 0. Also the Speed Level does not show current speed.

**Comment by mac8005** [comment]
this is my config:
` {
            "platform": "MiHumidifier",
            "devices": [
                {
                    "name": "Humidifier",
                    "address": "192.168.1.223",
                    "token": "xxx",
                    "model": "deerma.humidifier.jsq1",
                    "updateInterval": 30,
                    "ledBulb": {
                        "enabled": false,
                        "name": "Humidifier LED"
                    },
                    "buzzerSwitch": {
                        "enabled": false,
                        "name": "Humidifier Buzzer"
                    },
                    "temperatureSensor": {
                        "enabled": true,
                        "name": "Humidifier Temperature"
                    },
                    "humiditySensor": {
                        "enabled": true,
                        "name": "Humidifier Humidity"
                    }
                }
            ]
        },`

**Comment by russtone** [comment]
Could you please collect some debug logs by running homebridge like this:
`DEBUG=miio-api* homebridge`

**Comment by mac8005** [comment]
@russtone 
Can only find these Logs:
```
[12/17/2020, 9:17:16 AM] [MiHumidifier] Updating prop OnOff_State 0 0
[12/17/2020, 9:17:16 AM] [MiHumidifier] Updating prop Humidifier_Gear undefined 0
[12/17/2020, 9:17:16 AM] [MiHumidifier] Updating prop Humidity_Value undefined undefined
[12/17/2020, 9:17:16 AM] [MiHumidifier] Updating prop HumiSet_Value undefined undefined
[12/17/2020, 9:17:16 AM] [MiHumidifier] Updating prop waterstatus undefined NaN
[12/17/2020, 9:17:16 AM] [MiHumidifier] Updating prop TemperatureValue undefined undefined
```

**Comment by russtone** [comment]
Do you run homebridge using systemd service or using docker?

**Comment by mac8005** [comment]
Im running it with https://github.com/homebridge/homebridge-vm-image. I've just added the DEBUG_HOMEBRIDGE=1 to the Docker Compose

**Comment by russtone** [comment]
Could you also add environment variable `DEBUG=miio-api*` to your docker compose and try to collect some logs?

**Comment by mac8005** [comment]
```
[12/17/2020, 10:07:57 AM] [MiHumidifier] Updating prop OnOff_State 0 0
[12/17/2020, 10:07:57 AM] [MiHumidifier] Updating prop Humidifier_Gear undefined 0
[12/17/2020, 10:07:57 AM] [MiHumidifier] Updating prop Humidity_Value undefined undefined
[12/17/2020, 10:07:57 AM] [MiHumidifier] Updating prop HumiSet_Value undefined undefined
[12/17/2020, 10:07:57 AM] [MiHumidifier] Updating prop waterstatus undefined NaN
[12/17/2020, 10:07:57 AM] [MiHumidifier] Updating prop TemperatureValue undefined undefined
2020-12-17T09:07:57.367Z miio-api:device:02a99eju -> {
  id: 3141854682,
  method: 'get_prop',
  params: [
    'OnOff_State',
    'Humidifier_Gear',
    'Humidity_Value',
    'HumiSet_Value',
    'waterstatus',
    'TemperatureValue'
  ]
}
2020-12-17T09:07:57.367Z miio-api:device:02a99eju ->
0000    21 31 00 c0 00 00 00 00 0e 7b 3f 2e 00 00 fe 6d 
0010    21 6d 83 ae 8f 7b c4 bc e6 db ea e2 d6 bc 6a 05 
0020    01 f5 4b 16 4d 45 09 80 ad 01 b4 14 bb b1 3a 64 
0030    c5 37 b2 d9 26 80 99 e1 42 57 c0 86 7a 28 f1 fa 
0040    68 69 8e 9d 10 45 38 c5 6d cb 92 2f cd 69 6f 1e 
0050    dc c0 17 84 79 3b 29 52 46 2d d9 c0 dd 91 13 48 
0060    fb 73 24 99 15 ed dc be b2 05 86 e0 5c 22 52 74 
0070    41 94 92 81 63 04 64 55 1e 63 02 b4 33 f7 fa ea 
0080    b7 6a 91 33 6f 40 b1 c2 5c 58 7c 03 27 94 89 1e 
0090    78 b1 eb 36 48 f4 dc 13 80 05 0f 61 dd 74 1e 94 
00a0    f4 b6 bf 12 66 f3 c2 ee 65 a7 48 d2 b6 9f 80 9f 
00b0    a9 4e f6 e8 ab b6 3c 70 cc dd 5a 02 a1 6f f2 a1 
2020-12-17T09:07:57.627Z miio-api:device:02a99eju <-
0000    21 31 00 50 00 00 00 00 0e 7b 3f 2e 00 00 fe 6d 
0010    e1 d8 e4 59 8c a6 d7 4a 9a 3c b2 a0 be 5d 87 20 
0020    01 f5 4b 16 4d 45 09 80 ad 01 b4 14 bb b1 3a 64 
0030    aa 29 da 37 67 fa f9 0f 66 d5 22 5f 80 90 39 96 
0040    a9 7d fb 6f 59 7f 0d 56 6a b8 8a 8b 4f 56 31 13 
2020-12-17T09:07:57.628Z miio-api:device:02a99eju <- { id: 3141854682, result: [ 0 ], exe_time: 220 }
```

**Comment by russtone** [comment]
I think I found possible issue. Please, update to new version and test it again

**Comment by mac8005** [comment]
@russtone 
Thank you. Looks not bad now. Temperature and Humidity is working now. But i think the device gets many requests. When i run the plugin after some seconds/minutes i can no longer control the device in MI Home (Offline) and the Plugin shows timeouts:

```
    at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/17/2020, 11:54:39 AM] [MiHumidifier] Fail to get props. SocketError: Timeout
    at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
    at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/17/2020, 11:54:39 AM] [MiHumidifier] Fail to get props. SocketError: Timeout
    at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
    at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/17/2020, 11:54:39 AM] [MiHumidifier] Fail to get props. SocketError: Timeout
    at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
    at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/17/2020, 11:54:39 AM] [MiHumidifier] Fail to get props. SocketError: Timeout
    at /homebridge/node_modules/homebridge-mi-hum
    ```

**Comment by russtone** [comment]
I've published new version. Now properties will be requested sequentially, hope it helps

**Comment by mac8005** [comment]
Seams to be good now. Will leave it running for some hours and will report back to you.

**Comment by lvtz** [comment]
I've also noticed same spam in logs with this error: 'Fail to get props. SocketError: Timeout', it seems issue is not resolved. I've also mentioned this in #46

**Comment by chriz1984** [comment]
I have also problems with my `deerma.humidifier.jsq` with the old plugin version. Updated to `homebridge-mi-humidifier v2.0.0-beta.5` and will test now. Thanks for the Plugin!

**Comment by russtone** [comment]
> I've also noticed same spam in logs with this error: 'Fail to get props. SocketError: Timeout', it seems issue is not resolved. I've also mentioned this in #46

Are you getting these errors for jsq model?

**Comment by lvtz** [comment]
> > I've also noticed same spam in logs with this error: 'Fail to get props. SocketError: Timeout', it seems issue is not resolved. I've also mentioned this in #46
> 
> Are you getting these errors for jsq model?

I have `zhimi.humidifier.ca4` model. If this may help, I have two same devices connected with your plugin, maybe there is any complication if more than one device is connected?

**Comment by russtone** [comment]
I am closing this for now. If you find any problems with `deerma.humidifier.jsq` model support in the plugin, please create a new issue.
